name: build-macos

on: [push]

jobs:
  build:
    runs-on: macos-latest

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      PYTHON_CONFIGURE_OPTS: --enable-shared

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install obsolete python and pip
        uses: gabrielfalcao/pyenv-action@v5
        with:
          default: 2.7.13
          command: |
            easy_install pip
            pip install --upgrade pip

      - name: Install requirements
        run: |
          brew install libtiff libjpeg webp little-cms2
          brew install libxml2
          pip install lxml==2.2.8
          pip install py2app
          pip install Pillow==5.3.0
          pip install zope.interface
          pip install chardet
          pip install gitpython
          pip install suds
          pip install requests-oauthlib
          pip install python-dateutil
          pip install httplib2
          pip install beautifulsoup4
          pip install feedparser
          pip install oauthlib
          pip install webassets
          pip install cssmin

      - name: Create disk image
        run: hdiutil create -size 500m -layout GPTSPUD -fs 'Journaled HFS+' -type UDIF installs/osx/exe

      - name: Build package
        run: |
          cd installs/osx
          sed -i .bak 's/\/Volumes\/exe/\/Volumes\/untitled/g' make.py
          python make.py -p

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: exe-macos
          path: installs/osx/INTEF-exe-*.dmg
