name: build-macos

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          brew install pyenv
          env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 2.7.13
          pyenv shell 2.7.13
          easy_install pip
          brew install libjpeg
          pip install py2app
          pip install Pillow
          pip install zope.interface
          pip install libxml2
          pip install chardet
          pip install gitpython
          pip install lxml==2.2.8
          pip install suds
          pip install requests-oauthlib
          pip install python-dateutil
          pip install httplib2
          pip install beautifulsoup4
          pip install feedparser
          pip install oauthlib
          pip install webassets
          pip install cssmin

      - name: Create disk image
        run: hdiutil create -size 500m -layout GPTSPUD -fs 'Journaled HFS+' -type UDIF installs/osx/exe

      - name: Build package
        run: |
          cd installs/osx
          python make.py -p

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: exe.dmg
          path: installs/osx/exe.dmg
